apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: development
  labels:
    app: mysql 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql 
  template:
    metadata:
      labels:
        app: mysql 
    spec:
      containers:
      - name: mysql 
        image: mysql 
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: QRPAGE_SETTINGS_DATABASE_NAME
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: QRPAGE_SETTINGS_DATABASE_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: QRPAGE_SETTINGS_DATABASE_PASSWORD
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: QRPAGE_SETTINGS_DATABASE_ROOT

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: development
spec:
  selector:
    app: mysql 
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306 
