apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-django-deployment
  namespace: development
  labels:
    app: qr-django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qr-django
  template:
    metadata:
      labels:
        app: qr-django
    spec:
      containers:
      - name: qr-django
        image: qr-django:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: QRPAGE_SETTINGS_LOCAL_SETTINGS_PATH
          valueFrom:
            configMapKeyRef:
              name: qr-django-config
              key: QRPAGE_SETTINGS_LOCAL_SETTINGS_PATH
        - name: QRPAGE_SETTINGS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: qr-django-secret
              key: QRPAGE_SETTINGS_SECRET_KEY
        - name: QRPAGE_SETTINGS_ALLOWED_HOSTS
          valueFrom:
            secretKeyRef:
              name: qr-django-secret
              key: QRPAGE_SETTINGS_ALLOWED_HOSTS
        - name: QRPAGE_SETTINGS_CORS_ALLOWED_ORIGINS
          valueFrom:
            secretKeyRef:
              name: qr-django-secret
              key: QRPAGE_SETTINGS_CORS_ALLOWED_ORIGINS
        - name: QRPAGE_SETTINGS_MINIO_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: qr-django-config
              key: QRPAGE_SETTINGS_MINIO_ENDPOINT
        - name: QRPAGE_SETTINGS_MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: qr-django-secret
              key: QRPAGE_SETTINGS_MINIO_ACCESS_KEY
        - name: QRPAGE_SETTINGS_MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: qr-django-secret
              key: QRPAGE_SETTINGS_MINIO_SECRET_KEY
        - name: QRPAGE_SETTINGS_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: mysql-url
        - name: QRPAGE_SETTINGS_DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: qr-django-config
              key: QRPAGE_SETTINGS_DATABASE_PORT
        - name: QRPAGE_SETTINGS_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: QRPAGE_SETTINGS_DATABASE_NAME
        - name: QRPAGE_SETTINGS_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: QRPAGE_SETTINGS_DATABASE_USER
        - name: QRPAGE_SETTINGS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: QRPAGE_SETTINGS_DATABASE_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: qr-django-service
  namespace: development
spec:
  selector:
    app: qr-django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
